<?php

namespace Ardana\Archmap\Renderers;

use Ardana\Archmap\Contracts\Renderer;
use Ardana\Archmap\Graph\Graph;

final class MarkdownRenderer implements Renderer
{
    public function render(Graph $graph, array $context = []): string
    {
        $generatedAt = (string) ($context['generated_at'] ?? now()->toIso8601String());
        $routesMmd = (string) ($context['routes_mmd'] ?? '');
        $erdMmd = (string) ($context['erd_mmd'] ?? '');
        $classesMmd = (string) ($context['classes_mmd'] ?? '');
        $componentsMmd = (string) ($context['components_mmd'] ?? '');
        $issues = (array) ($context['issues'] ?? []);
        $stats = (array) ($context['stats'] ?? []);

        $markdown = [];
        $markdown[] = '# Architecture Documentation';
        $markdown[] = '';
        $markdown[] = 'Generated by Laravel Archmap on '.$generatedAt.'.';
        $markdown[] = '';
        $markdown[] = '## Project Summary';
        $markdown[] = '';
        $markdown[] = '- Routes: '.(int) ($stats['routes'] ?? 0);
        $markdown[] = '- Models: '.(int) ($stats['models'] ?? 0);
        $markdown[] = '- Classes: '.(int) ($stats['classes'] ?? 0);
        $markdown[] = '';
        $markdown[] = '## Route Map';
        $markdown[] = '';
        $markdown[] = '```mermaid';
        $markdown[] = trim($routesMmd);
        $markdown[] = '```';
        $markdown[] = '';
        $markdown[] = '## ERD';
        $markdown[] = '';
        $markdown[] = '```mermaid';
        $markdown[] = trim($erdMmd);
        $markdown[] = '```';
        $markdown[] = '';
        $markdown[] = '## Class Diagram';
        $markdown[] = '';
        $markdown[] = '```mermaid';
        $markdown[] = trim($classesMmd);
        $markdown[] = '```';
        $markdown[] = '';
        $markdown[] = '## Component Diagram';
        $markdown[] = '';
        $markdown[] = '```mermaid';
        $markdown[] = trim($componentsMmd);
        $markdown[] = '```';
        $markdown[] = '';
        $markdown[] = '## Architecture Health Report';
        $markdown[] = '';
        $markdown[] = '| Severity | Item | Recommendation |';
        $markdown[] = '|---|---|---|';

        foreach ($issues as $issue) {
            if (!is_array($issue)) {
                continue;
            }
            $markdown[] = sprintf(
                '| %s | %s | %s |',
                $issue['severity'] ?? 'info',
                str_replace('|', '\\|', (string) ($issue['message'] ?? '')),
                str_replace('|', '\\|', (string) ($issue['recommendation'] ?? ''))
            );
        }

        return implode(PHP_EOL, $markdown).PHP_EOL;
    }
}
